config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  get 'attendances/create'
  resources :users, only: %i[new create show]
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in_new'
  get '/sign_out', to: 'users#sign_out'
  post '/sign_in', to: 'events#enroll'
  resources :events, only: %i[new create show index]
  resources :attendances
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :attendances
  has_many :attendee, through: :attendances, source: :user

  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true

  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ? ', DateTime.now) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date < ? ', Date.today) }
end

app/controllers/application_controller.rb
require 'date'
class ApplicationController < ActionController::Base
  def date_now
    date = DateTime.now
    date.localtime.strftime('%m/%d/%Y %H:%M')
  end
  helper_method :current_user_now
  def current_user_now
    User.find(session[:current_user]['id'])
  end
end

app/controllers/attendances_controller.rb
# rubocop:disable Layout/LineLength

class AttendancesController < ApplicationController
  def create
    if User.find(params[:user][:user_id]).attendances.where(event_id: params[:event_id]).none?
      user = User.find(params[:user][:user_id])
      a = Attendance.new(event_id: params[:event_id], user_id: user.id)
      a.save
      msg = build_msg
    else
      msg = "You are already attending to #{Event.find(params[:event_id]).name}"
    end
    redirect_to event_path(params[:event_id]), notice: msg
  end

  private

  def build_msg
    if (params[:user][:user_id]).to_i == session[:current_user]['id']
      msg = "You decided to attend #{Event.find(params[:event_id]).name}"
    else
      msg = "You decided to invite #{User.find(params[:user][:user_id]).username} to attend #{Event.find(params[:event_id]).name}"
    end
    msg
  end
end

# rubocop:enable Layout/LineLength

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  include UsersHelper

  def index
    @upcoming = Event.upcoming.sort { |a, b| b.date <=> a.date }
    @past = Event.past.sort { |a, b| b.date <=> a.date }
  end

  def show
    if session[:current_user]
      @event = Event.find(params[:id])
      @date = date_now
      @attendance = Attendance.new
      @users_not_in = User.all.where.not(id: @event.attendee).where.not(id: session[:current_user]['id'])
    else
      redirect_to sign_in_path
    end
  end

  def create
    user = User.find(session[:current_user]['id'])
    @event = user.events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def new
    if session[:current_user]
      @event = Event.new
    else
      redirect_to sign_in_path
    end
  end

  def enroll
    @user = User.find_by(username: params[:username])
    current_user(@user.id) if @user && params[:password] == @user.password
    # post sign_in_path, username: 'marcelomaidden', password: '12345678'
  end
end

app/controllers/users_controller.rb
require 'date'

class UsersController < ApplicationController
  include UsersHelper

  def new
    if session[:current_user]
      redirect_to events_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      current_user(@user.id)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    if session[:current_user]
      @user = User.find(params[:id])
      current_user(@user.id)
      @date = date_now
      @attended_events = @user.attended_events.sort { |a, b| b.date <=> a.date }
      @upcoming = @user.attended_events.upcoming
      @past = @user.attended_events.past
      @my_events = @user.events
    else
      redirect_to sign_in_path
    end
  end

  def sign_in_new
    @user = User.find_by(username: params[:username])
    if @user && params[:password] == @user.password
      current_user(@user.id)
      redirect_to root_path
    else
      redirect_to sign_in_path, notice: 'User or password wrong'
    end
  end

  def sign_in
    redirect_to events_path if session[:current_user]
  end

  def sign_out
    reset_session
    redirect_to sign_in_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?
    session[:current_user] = User.find(params[:id])
    session[:current_user]
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:name, :description, :date, :creator_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user(id)
    session[:current_user] = User.find(id)
    session[:current_user]
  end

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/views/events/index.html.erb
<h1>All Events</h1>

<% if !Event.any? %>
  <h2>No events</h2>
<% else %>
  <div class="upcoming-cont">
    <% if @upcoming.any? %>
      <h2>Upcoming Events</h2>
      <ul class = "upcoming">
        <% @upcoming.each do |e| %>
            <li>
              <% if session[:current_user] %>
                <%= link_to  e.name, event_path(e.id) %>
              <% else %>
                <%= link_to  e.name, sign_in_path %>
              <% end %>
              <div>
                <%= content_tag(:p, "Event Date: #{e.date.localtime.strftime("%m/%d/%Y")} Time: #{e.date.localtime.strftime("%H:%M")}", class: "date-time") %>
              </div>
            </li>
        <%end%>
      </ul>
    <% end %>
  </div>

  <div class="past-cont">
    <% if @past.any? %>
      <h2>Past Events</h2>
      <ul class = "past">
        <% @past.each do |e| %>
            <li>
              <% if session[:current_user] %>
                <%= link_to  e.name, event_path(e.id) %>
              <% else %>
                <%= link_to  e.name, sign_in_path %>
              <% end %>
            <div>
              <%= content_tag(:p, "Event Date: #{e.date.localtime.strftime("%m/%d/%Y")} Time: #{e.date.localtime.strftime("%H:%M")}", class: "date-time") %>
            </div>
            </li>
        <%end%>
      </ul>
    <%end%>
  </div>
<% end %>

app/views/events/new.html.erb
<% if session[:current_user] %>
  <%= link_to  "< Back to My Events", user_path(session[:current_user]['id']), class: "back-to" %>
<% end %>

<h1 class="create-title">Create an Event</h1>

<%= form_for @event, html: { class: "event-form" } do |f| %>
  <%= f.label :name, 'Event Name', class: "name-label" %>
  <%= f.text_field :name, class: "name" %>
  <%= f.label :description, 'Event description', class: "desc-label" %>
  <%= f.text_area :description, class: "desc" %>
  <%= f.label :date, 'Event Date', class: "date-label" %>
  <div>
  <%= f.datetime_select :date, ampm: true, order: %i[day month year], default: 0.days.from_now.localtime, class: "date" %>
  </div>
  <%= f.submit 'Create Event', class: "create-btn" %>

  <% @event.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

app/views/events/show.html.erb
<%= link_to  "< Back to events", events_path, class: "back-to" %>
<p class="flash-events"><%=flash.notice%></p>
<h1><%= @event.name %></h1>

<label>Event Description:</label><br />
<%= @event.description %><br /><br />
<label>Event Date:</label><br />
<%= @event.date.localtime.strftime("%m/%d/%Y %H:%M") %><br />

<br />
<% if @event.attendee.any? %>
<h3>Attendees</h3>
<ul>
  <% @event.attendee.each do |a| %>
    <li>
      <%= a.username %>
    </li>
  <% end %>
</ul>
<% end %>

<% if @event.date.localtime.strftime("%m/%d/%Y %H:%M") > @date %>
  <% if session[:current_user] && !current_user_now.attended_events.where(id: @event.id).any? %>
    <%= form_for @attendance do |f| %>
      <%= hidden_field_tag :event_id, @event.id %>
      <%=hidden_field_tag :user_id, session[:current_user]['id'], {id: 'user_user_id', name: 'user[user_id]'}%>
      <%= f.submit 'Attend' %>
    <% end %>
  <% end %>

  <% if @users_not_in.any? %>
    <h3>Invite user</h3>
    <%= form_for @attendance do |f| %>
      <%= hidden_field_tag :event_id, @event.id %>
      <%= select("user", "user_id", @users_not_in.collect {|p| [ p.username, p.id ] }, class: 'invitee') %>
      <%= f.submit 'Invite', class: 'invite-btn' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="nav">
          <%= link_to  "All Events", events_path %>

          <% if session[:current_user].nil?%>
            <%= link_to  "Register", new_user_path %>
            <%= link_to  "Login", sign_in_path %>
          <%else%>
            <%= link_to  'My Events', user_path(session[:current_user]['id']) %>
            <%= link_to  "Sign-out", sign_out_path %>
          <%end%>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1 class="register-title">Register</h1>

<%= form_for @user, html:{ class: "register-form" } do |f| %>
  <%= f.label :username, 'Username', class: "username-label" %>
  <%= f.text_field :username, class: "username" %>
  <%= f.label :password, 'Password', class: "password-label" %>
  <%= f.password_field :password, class: "password" %>
  <%= f.label :email, 'Email', class: "email-label" %>
  <%= f.email_field :email, class: "email" %>
  <%= f.submit 'Register', class: "register-btn" %>

  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>All My Events</h1>
<div class="create-cont">
  <div class="create-btn">
    <%= link_to  "Create Event", new_event_path %>
  </div>
</div>

<% if @user.attended_events.none? && @my_events.none?%>
  <h3>You don't have any Events</h3>
<% else %>
  <% if @upcoming.any? %>
    <div class="upcoming-cont">
      <h2>Upcoming Events</h2>
      <ul class="events">
        <% @attended_events.each do |e| %>
          <% if e.date.localtime.strftime("%m/%d/%Y %H:%M") >= @date %>
          <li>
            <%= link_to  e.name , event_path(e.id) %>
            <%= content_tag(:p, "Event Date: #{e.date.localtime.strftime("%m/%d/%Y")} Time: #{e.date.localtime.strftime("%H:%M")}", class: "date-time") %>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>


  <% if @past.any? %>
    <div class="past-cont">
      <h2>Past Events</h2>
      <ul class="events">
        <% @attended_events.each do |e| %>
          <% if e.date.localtime.strftime("%m/%d/%Y %H:%M") < @date %>
            <li>
              <%= link_to  e.name , event_path(e.id) %>
              <%= content_tag(:p, "Event Date: #{e.date.localtime.strftime("%m/%d/%Y")} Time: #{e.date.localtime.strftime("%H:%M")}", class: "date-time") %>
            </li>
          <% end %>
        <%end%>
      </ul>
    </div>
  <% end %>
<% end %>

<% if @my_events.any? %>
  <div class="my-events-cont">
    <h2>Created Events</h2>
    <ul class="my-events">
      <% @my_events.each do |me| %>
        <li>
          <%= link_to  me.name, event_path(me.id) %>
          <%= content_tag(:p, "Event Date: #{me.date.localtime.strftime("%m/%d/%Y")} Time: #{me.date.localtime.strftime("%H:%M")}", class: "date-time") %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/sign_in.html.erb
<h1 class="login-title">Login</h1>
<%= form_with model: @user, class: "login-form" do |f| %>
  <%= f.label :username, class: "username-label" %>
  <%= f.text_field :username, class: "username" %>
  <%= f.label :password, class: "password-label" %>
  <%= f.password_field :password, class: "password" %>
  <%= f.submit 'Login', class: "login-btn" %>
  <div class="register-btn">
    <%= link_to  "Register", new_user_path %>
  </div>
  <p class="flash"><%=flash.notice%></p>
<% end %>